### ISSUE TITLE
Lifecycle

### ISSUE THREAD

**Issue by jabbett** [datuhealth/chaperone#1]
We're considering using Chaperone for our single-page app, potentially on several different views. When a view is destroyed, how do we de-initialize a tour? (i.e. remove all event handlers, etc.)

**Comment by spacecowboyian** [comment]
Presently I only have the endTour method that removes all of the throbbers and the body/container class for chaperone. I'll look into expanding it to remove the event handlers as well.

**Comment by spacecowboyian** [comment]
Updated the endTour method to include event unbinding. I haven't tested it on an SPA but give it a shot and let me know how it goes.
